# Generated by Django 3.0.5 on 2020-08-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='app_doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='name',
        ),
    ]
